workspace:
        base: /go
        path: src/github.com/f6systems/iam

pipeline:
        build:
         image: golang
         commands:
                - go get github.com/f6systems/iam
                - go build -v
                - go test -v


